version: '0.1.0.{build}'

clone_folder: c:\GoDev\src\github.com\appplant\alpinepass

environment:
  GOPATH: c:\GoDev

install:
  - cd src
  - go get -v

build_script:
  - go version
  - go env
  - go build -o alpinepass

test_script:
  - go test ./...
